sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t rajatk31/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rajatk31/react-test npm test

after_success:
  - docker build -t rajatk31/multi-dock-client ./client
  - docker build -t rajatk31/multi-dock-nginx ./nginx
  - docker build -t rajatk31/multi-dock-server ./server
  - docker build -t rajatk31/multi-dock-worker ./worker

  #Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take these images and push them to docker hub.
  - docker push rajatk31/multi-dock-client
  - docker push rajatk31/multi-dock-worker
  - docker push rajatk31/multi-dock-server
  - docker push rajatk31/multi-dock-nginx

deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-south-1-282148214463
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY